name: NPM Publishing

on:
  #release:
    #types: [created]
  workflow_dispatch:
  workflow_call:
  #workflow_run:
    #workflows: ["Create New Release"]
    #types:
      #- completed         
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: â˜ Checkout
        uses: actions/checkout@v2
      - name: â¬‡ Install npm
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm ci
  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: â˜ Checkout
        uses: actions/checkout@v2
      - name: â¬‡ Install npm
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - name: ğŸ‘‘ Publish npm package
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.TSS_NPM_TOKEN}}